// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type AccountList struct {
	ID              int32
	Name            string
	AccountNumber   string
	ProductType     string
	AccountType     int32
	Bank            string
	Currency        string
	AccountTypeCode string
	IsDefault       sql.NullString
	CreatedAt       sql.NullTime
}
